[package]
name = "sc-consensus-poc"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>", "Subspace Labs <admin@subspace.network>"]
description = "PoC consensus algorithm for substrate"
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://subspace.network"
repository = "https://github.com/subspace/substrate"
documentation = "https://docs.rs/sc-consensus-poc"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", features = ["derive"] }
sp-consensus-poc = { version = "0.1.0", path = "../../../primitives/consensus/poc" }
sc-consensus = { version = "0.10.0-dev", path = "../../../client/consensus/common" }
sp-core = { version = "4.0.0-dev", path = "../../../primitives/core" }
num-bigint = "0.2.3"
num-rational = "0.2.2"
num-traits = "0.2.14"
serde = { version = "1.0.127", features = ["derive"] }
sp-version = { version = "4.0.0-dev", path = "../../../primitives/version" }
sp-io = { version = "4.0.0-dev", path = "../../../primitives/io" }
sp-inherents = { version = "4.0.0-dev", path = "../../../primitives/inherents" }
sc-telemetry = { version = "4.0.0-dev", path = "../../telemetry" }
sc-keystore = { version = "4.0.0-dev", path = "../../keystore" }
sc-client-api = { version = "4.0.0-dev", path = "../../api" }
sc-consensus-epochs = { version = "0.10.0-dev", path = "../epochs" }
sp-api = { version = "4.0.0-dev", path = "../../../primitives/api" }
sp-block-builder = { version = "4.0.0-dev", path = "../../../primitives/block-builder" }
sp-blockchain = { version = "4.0.0-dev", path = "../../../primitives/blockchain" }
sp-consensus = { version = "0.10.0-dev", path = "../../../primitives/consensus/common" }
sp-consensus-slots = { version = "0.10.0-dev", path = "../../../primitives/consensus/slots" }
sp-consensus-spartan = { version = "0.1.0", path = "../../../primitives/consensus/spartan" }
sc-consensus-uncles = { version = "0.10.0-dev", path = "../uncles" }
sc-consensus-slots = { version = "0.10.0-dev", path = "../slots" }
sp-runtime = { version = "4.0.0-dev", path = "../../../primitives/runtime" }
sp-utils = { version = "4.0.0-dev", path = "../../../primitives/utils" }
fork-tree = { version = "3.0.0", path = "../../../utils/fork-tree" }
prometheus-endpoint = { package = "substrate-prometheus-endpoint", path = "../../../utils/prometheus", version = "0.9.0"}
futures = "0.3.16"
futures-timer = "3.0.2"
parking_lot = "0.11.1"
log = "0.4.14"
schnorrkel = { version = "0.9.1" }
rand = "0.7.2"
merlin = "2.0"
derive_more = "0.99.17"
async-trait = "0.1.51"
ring = "0.16"

[dev-dependencies]
sp-timestamp = { version = "4.0.0-dev", path = "../../../primitives/timestamp" }
sp-tracing = { version = "4.0.0-dev", path = "../../../primitives/tracing" }
sc-executor = { version = "0.10.0-dev", path = "../../executor" }
sc-network = { version = "0.10.0-dev", path = "../../network" }
sc-network-test = { version = "0.8.0", path = "../../network/test" }
sc-service = { version = "0.10.0-dev", default-features = false, path = "../../service" }
substrate-test-runtime-client = { version = "2.0.0", path = "../../../test-utils/runtime/client" }
sc-block-builder = { version = "0.10.0-dev", path = "../../block-builder" }
spartan-codec = "0.1.0"
